version: "3"

services:
  sonarqube:
    image: sonarqube:latest
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
  apache:
    image: httpd:latest
    container_name: apache-server
    ports:
      - 8080:80

#docker-compose    -f  docker-compose-2.yaml  up -d 
