version: '3.1'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: teste
    volumes:
      - ./dbdados:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 80:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql  

  rabbit:
    image: rabbitmq:3.8-management
    container_name: rabbitmq38
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq

  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    ports:
      - 6379:6379

  redisInterfaceAdmin:
    image: marian/rebrow
    container_name: redisInterfaceAdmin
    ports: 
      - 5001:5001
    depends_on:
      - redis

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  default:
    external:
      name: external-example

#docker-compose  up -d 