spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:clines}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create

cors:
  allowed:
    origins: ${CORS_HOST:http://localhost:3000}
    all-methods: true
    all-headers: true
    send-credentials: true