version: "3.9"
services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clines
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    image: caelum/clines
    environment:
      DB_HOST: database
    ports:
      - 9090:8080
    depends_on:
      - database

volumes:
  db-volume:

#docker-compose up -d
#docker compose down
#docker compose logs
